### ISSUE TITLE
Joomla 3.8.4 Issue with PHP 7.1 Class and Function Name

### ISSUE THREAD

**Issue by matthewbpetro** [tawk/tawk-joomla#1]
When adding this to our Joomla production site I found an error listed that the class and function have the same name. This is no longer supported in PHP 7.1, I was able to easily modify the function name simply by adding another letter to the name of function and it worked without issue.

class plgSystemtawkto extends JPlugin
function plgSystemtawkto( &$subject, $params )

**Comment by Harjinderkour** [comment]
I am very interested and would like this opportunity to work for me but I don't know what I do my bubble I'd is very confused on the way,

**Comment by hertzli** [comment]
Matthew is 100% spot on.  In the file ./plugins/system/tawkto/tawkto.php, you will need to change the line 
function plgSystemtawkto( &$subject, $params )
into e.g.
function plgMyOwnSystemtawkto( &$subject, $params )

In my specific environment, it would be the file
/home/hertzli/public_html/plugins/system/tawkto/tawkto.php

After saving the tawkto.php file, the warning is gone.
/Per
